# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2" # Vagrantfile API/syntax version.

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  # Indicates which box is using this project.
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Network settings of the VM machine.
  config.vm.network :private_network, ip: "192.168.40.121"
  config.ssh.forward_agent = true

  # Settings of the Provider used.
  config.vm.provider :virtualbox do |v|
    v.gui = FALSE
    v.name = "Puppet vagrant demo"
    v.customize ["modifyvm", :id, "--memory", "1624"]
    #v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    #v.customize ["modifyvm", :id, "--memory", 1512]
    #v.customize ["modifyvm", :id, "--name", "drupal-vagrant-demo"]
  end

  nfs_setting = RUBY_PLATFORM =~ /darwin/ || RUBY_PLATFORM =~ /linux/
#  config.vm.synced_folder "/var/www/vagrant-demo/demo/src/drupal/", "/var/www/drupal", id: "vagrant-root" , :nfs => nfs_setting
  config.vm.synced_folder "/var/www/vagrant-demo/demo/src/drupal/", "/var/www/drupal", id: "vagrant-root" 
  
  # Provision settings.
  config.vm.provision :shell, :inline =>
    "if [[ ! -f /apt-get-run ]]; then sudo apt-get update && sudo touch /apt-get-run; fi"


  config.vm.provision :shell, :inline => 'echo -e "mysql_root_password=root
    controluser_password=awesome" > /etc/phpmyadmin.facts;'

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "default.pp"
    puppet.module_path = "puppet/modules"
    # puppet.options = ['--verbose --debug']
  end
end
